In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:

import pandas as pd

import numpy as np
from tlpath.utils import (
    predict_telomere_length,
    predict_all_tissues,
    predict_batch,
)



### Define Model directory

In [ ]:
models_dir = '/shares/sinha/anamikay/TLPath_results/models'

### Read your dataset

In [ ]:
# Read Pancreas features
pancreas_df = pd.read_csv('example_data/Pancreas.csv')
pancreas_feature = np.fromstring(pancreas_df['features'].iloc[0], sep=',')

# Read Lung features
lung_df = pd.read_csv('example_data/Lung.csv')
lung_feature = np.fromstring(lung_df['features'].iloc[0], sep=',')

# Read Prostate features
prostate_df = pd.read_csv('example_data/Prostate.csv')
prostate_feature = np.fromstring(prostate_df['features'].iloc[0], sep=',')

# Verify the shape and contents
print("Pancreas feature shape:", pancreas_feature.shape)
print("Lung feature shape:", lung_feature.shape)
print("Prostate feature shape:", prostate_feature.shape)

# Optional: Confirm the first few values match the original
print("\nFirst 5 values of Pancreas feature:")
print(pancreas_feature[:5])
print("\nFirst 5 values of Lung feature:")
print(lung_feature[:5])
print("\nFirst 5 values of Prostate feature:")
print(prostate_feature[:5])

Pancreas feature shape: (1024,)
Lung feature shape: (1024,)
Prostate feature shape: (1024,)

First 5 values of Pancreas feature:
[-0.47796673  0.5678965  -0.0070671  -0.3450487  -0.8205662 ]

First 5 values of Lung feature:
[ 1.2019104  -1.8069416   0.9060353  -0.72513616 -0.87671965]

First 5 values of Prostate feature:
[-2.1857305   0.73711205  0.6619406  -0.2543194   0.43601274]


### Run inference

In [20]:
# Single tissue prediction
telomere_length_pancreas = predict_telomere_length(models_dir, pancreas_feature, "Pancreas")

In [21]:
print(f'Predicted Telomere length for pancreatic Sample is {telomere_length_pancreas}')

Predicted Telomere length for pancreatic Sample is [0.90414792]


In [22]:
# Multiple tissue prediction
tissue_features = {
    "Pancreas": pancreas_feature,
    "Lung": lung_feature,
    "Prostate": prostate_feature
}
all_predictions = predict_all_tissues(models_dir, tissue_features)


In [25]:
all_predictions['Pancreas']

array([0.90414792])

all_predictions

In [30]:
print('Predicted Telomere length for pancreatic Sample is: ', all_predictions['Pancreas'])
print('Predicted Telomere length for lung Sample is: ', all_predictions['Lung'])
print('Predicted Telomere length for prostate Sample is: ', all_predictions['Prostate'])


Predicted Telomere length for pancreatic Sample is:  [0.90414792]
Predicted Telomere length for lung Sample is:  [0.82714514]
Predicted Telomere length for prostate Sample is:  [0.93589242]


In [ ]:

# # Batch prediction for large datasets
# large_features = np.array([...])  # Large dataset
# batch_predictions = tlpath.predict_batch(large_features, "Lung", batch_size=64)